name: 'FrenchTexan Photography '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33293
title: More than the eye can see...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9d9f2'
    - '#020000'
    - '#6e7fa9'
    - '#ad0000'
    - '#2c4f9d'
  brandStrength: 0.827259
  lightness: 0.3060949
  saturation: 0.5082967
  rhythmicContrast: 0.1415771
purpose: []
