layout_spectrum: 1
color:
  saturation: 0.5082967
  lightness: 0.3060949
  brandStrength: 0.827259
  brandColors:
    - '#E1E7F3'
    - '#010002'
    - '#CF0102'
    - '#010377'
    - '#2777CF'
  rhythmicContrast: 0.1415771
typography_spectrum: 0.3763441
name: 'FrenchTexan Photography '
